/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.TipoChamado;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-08-24T23:05:39.296Z")

@Api(value = "tipoChamado", description = "the tipoChamado API")
@RequestMapping(value = "/api")
public interface TipoChamadoApi {

    @ApiOperation(value = "Parametriza novo tipoChamado.", nickname = "cadastrarTipoChamado", notes = "EndPoint Parametriza novo tipoChamado.", tags={ "TipoChamado", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Operação realizada com sucesso."),
        @ApiResponse(code = 405, message = "Entrada inválida."),
        @ApiResponse(code = 500, message = "Erro Interno.") })
    @RequestMapping(value = "/tipoChamado/cadastrarTipoChamado",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> cadastrarTipoChamado(@ApiParam(value = "EndPoint Parametriza novo tipoChamado." ,required=true )  @Valid @RequestBody TipoChamado body);

}
