/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package br.com.open.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import br.com.open.model.TipoChamado;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-08-24T23:05:39.296Z")

@Api(value = "tipoChamado", description = "the tipoChamado API")
@RequestMapping(value = "/api")
public interface TipoChamadoApi {

    @ApiOperation(value = "Parametriza novo tipoChamado.", nickname = "cadastrarTipoChamado", notes = "EndPoint Parametriza novo tipoChamado.", tags={ "TipoChamado", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Operação realizada com sucesso."),
        @ApiResponse(code = 405, message = "Entrada inválida."),
        @ApiResponse(code = 500, message = "Erro Interno.") })
    @RequestMapping(value = "/tipoChamado/cadastrarTipoChamado",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> cadastrarTipoChamado(@ApiParam(value = "EndPoint Parametriza novo tipoChamado." ,required=true )  @Valid @RequestBody TipoChamado body);

}
